/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 *//*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kwa.cj.modules.t010;

import com.kwa.cj.views.*;
import com.kwa.cj.modules.t010.T010CBModel;
import com.kwa.cj.modules.t010.T010CBRender;
import com.kwa.cj.modules.t010.T010JpaController;
import com.kwa.core.KWAMesg;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import org.eclipse.persistence.descriptors.TimestampLockingPolicy;

/**
 *
 * @author arinegara
 */
public class VT010Search extends javax.swing.JPanel {

    /**
     * Creates new form VPegawai
     */
    public VT010Search() {
        initComponents();
        initValues();
    }

    private void initTab() throws Exception{
                   pegp = new TpegawaiJpaController(null, null);
            modelPegawai mp = new modelPegawai(pegp);
            mp.searchAll();
              tabPegawai = new javax.swing.JTable();
            list = mp.getData();
            tabPegawai.setModel(mp); 
            

            
   
          
                  tabPegawai.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabPegawai.getSelectionModel().addListSelectionListener(new RowListener());
        tabPegawai.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabPegawai);
       
    }
    private void initValues() {
        try {
            initTab();


            T010JpaController t010p = new T010JpaController(pegp.getEmf(), pegp.getEm());
            T010CBModel t010cbmodel = new T010CBModel(t010p, "TSPG", "", "");
            cbStatus.setModel(t010cbmodel);
            cbStatus.setRenderer(new T010CBRender(t010p, "TSPG"));

        } catch (Exception ex) {
            Logger.getLogger(VPegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabPegawai = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtKeyword = new javax.swing.JTextField();

        tabPegawai.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabPegawai.getSelectionModel().addListSelectionListener(new RowListener());
        tabPegawai.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabPegawai);

        jToolBar1.setRollover(true);

        btnNew.setText("new");
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doNew(evt);
            }
        });
        jToolBar1.add(btnNew);
        jToolBar1.add(jSeparator3);

        btnSearch.setText("search");
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSearch);

        jLabel1.setText("Keyword :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doNew(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doNew
        txtKeyword.setText("");
        txtNama.setText("");
        cbStatus.setSelectedItem("A");
    }//GEN-LAST:event_doNew

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tabPegawai;
    private javax.swing.JTextField txtKeyword;
    // End of variables declaration//GEN-END:variables
    private T010 t010E;
    private T010JpaController t010C;
    private java.util.List<com.kwa.cj.modules.t010.T010> list;

    private class RowListener implements ListSelectionListener {
        
        public void valueChanged(ListSelectionEvent event) {
            if (event.getValueIsAdjusting()) {
                return;
            }
            tabPegawai.getSelectedRow();
            modelPegawai modelpeg = (modelPegawai) tabPegawai.getModel();
            peg =  modelpeg.getData().get(tabPegawai.getSelectedRow());
            txtKeyword.setText(peg.getKode());
            txtNama.setText(peg.getNama());
            cbStatus.setSelectedItem(peg.getStatus());
        }
    }

}
