/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kwa.cj.views;

import com.kwa.cittajaya.T010JpaController;
import com.kwa.cittajaya.Tkatalog;
import com.kwa.cittajaya.TkatalogJpaController;
import com.kwa.cittajaya.Ttransbrgheader;
import com.kwa.cittajaya.TtransbrgheaderJpaController;
import com.kwa.cittajaya.Ttransbrgitem;
import com.kwa.cittajaya.TtransbrgitemJpaController;
import com.kwa.core.KWAMesg;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author arinegara
 */
public class VTransaksi extends javax.swing.JPanel {

    /**
     * Creates new form VKatalog
     */
    public VTransaksi() {
        initComponents();
        initValues();
    }

    private void initTab() throws Exception{
                   tbip = new TtransbrgitemJpaController(tbhp.getEmf(), tbhp.getEm());
            modelTransItem mti = new modelTransItem(tbip);
            mti.searchAll(txtKode.getText());
              tabItem = new javax.swing.JTable();
            list = mti.getData();
            tabItem.setModel(mti); 
            

            
   
          
                  tabItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabItem.getSelectionModel().addListSelectionListener(new RowListener());
        tabItem.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabItem);
       
    }
    private void initValues() {
        try {
            tbhp = new TtransbrgheaderJpaController(null,null);
            initTab();


            T010JpaController t010p = new T010JpaController(tbhp.getEmf(), tbhp.getEm());
            T010CBModel t010cbmodel = new T010CBModel(t010p, "TSB", "", "");
            cbSatuan.setModel(t010cbmodel);
            cbSatuan.setRenderer(new T010CBRender(t010p, "TSB"));

            
            t010cbmodel = new T010CBModel(t010p, "TTBH", "", "");
            cbTipe.setModel(t010cbmodel);
            cbTipe.setRenderer(new T010CBRender(t010p, "TTBH"));

            
        } catch (Exception ex) {
            Logger.getLogger(VTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabItem = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSave = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnDelete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        cbTipe = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        lblToko = new javax.swing.JLabel();
        txtKlien = new javax.swing.JTextField();
        txtPegawai = new javax.swing.JTextField();
        lblPegawai = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        lblBarang = new javax.swing.JLabel();
        txtKodeBrg = new javax.swing.JTextField();
        lblTokoDesc = new javax.swing.JLabel();
        lblPegawaiDesc = new javax.swing.JLabel();
        lblBarangDesc = new javax.swing.JLabel();
        cbSatuan = new javax.swing.JComboBox();
        lblBarang2 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JFormattedTextField();
        lblBarang3 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JFormattedTextField();
        lblBarang4 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JFormattedTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        tabItem.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabItem.getSelectionModel().addListSelectionListener(new RowListener());
        tabItem.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabItem);

        jToolBar1.setRollover(true);

        btnNew.setText("new");
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doNew(evt);
            }
        });
        jToolBar1.add(btnNew);
        jToolBar1.add(jSeparator1);

        btnSave.setText("save");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doSave(evt);
            }
        });
        jToolBar1.add(btnSave);
        jToolBar1.add(jSeparator2);

        btnDelete.setText("delete");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);
        jToolBar1.add(jSeparator3);

        btnSearch.setText("search");
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSearch);

        jLabel1.setText("Kode :");

        cbTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipeActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipe :");

        jXDatePicker1.setEditable(false);

        jLabel5.setText("Tanggal :");

        lblToko.setText("Toko :");

        lblPegawai.setText("Pegawai :");

        jLabel8.setText("Keterangan : ");

        lblBarang.setText("Barang : ");
        lblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cariBarang(evt);
            }
        });

        lblTokoDesc.setText("jLabel3");

        lblPegawaiDesc.setText("jLabel3");

        lblBarangDesc.setText("Barang : ");
        lblBarangDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBarangDesccariBarang(evt);
            }
        });

        cbSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSatuanActionPerformed(evt);
            }
        });

        lblBarang2.setText("Jumlah : ");
        lblBarang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBarang2cariBarang(evt);
            }
        });

        txtJumlah.setText("jFormattedTextField1");

        lblBarang3.setText("Harga :");
        lblBarang3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBarang3cariBarang(evt);
            }
        });

        txtHarga.setText("jFormattedTextField1");

        lblBarang4.setText("Discount :");
        lblBarang4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBarang4cariBarang(evt);
            }
        });

        txtDiscount.setText("jFormattedTextField1");

        btnAdd.setText("add");

        btnRemove.setText("remove");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblToko)
                                    .addComponent(lblPegawai))
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKeterangan)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPegawaiDesc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtKlien, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTokoDesc)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBarang)
                                .addGap(18, 18, 18)
                                .addComponent(txtKodeBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBarangDesc))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBarang2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBarang3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75)
                                        .addComponent(lblBarang4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemove)
                                    .addComponent(btnAdd))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
            .addComponent(jSeparator6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKlien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblToko)
                            .addComponent(lblTokoDesc))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPegawai)
                            .addComponent(lblPegawaiDesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarang)
                    .addComponent(txtKodeBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBarangDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarang2)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarang3)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBarang4)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doNew(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doNew
        /*txtKode.setText("");
        
        cbTipe.setSelectedIndex(0);
        txtArtikel.setText("");
        txtUkuran.setText("");
        txtWarna.setText("");
        cbTipe.setSelectedItem("N");
        
        */
    }//GEN-LAST:event_doNew

    private void doSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doSave
        /*
        katalog = new Tkatalog(txtKode.getText().trim(),(String) cbMerk.getSelectedItem(), txtArtikel.getText().trim(), txtUkuran.getText().trim(), txtWarna.getText(),(String) cbTipe.getSelectedItem(),null);
        // pegp.commitTrx();
        try{
           
            katalogp = new TkatalogJpaController(null,null);
            KWAMesg msg;
            katalogp.initTrx();
            if(katalogp.findTkatalog(txtKode.getText())==null){
                msg = katalogp.create(katalog);
                JOptionPane.showMessageDialog(null, msg.getMesg(),"Create",1);
            }else{
                msg = katalogp.edit(katalog);
                JOptionPane.showMessageDialog(null, msg.getMesg(),"Modify",1);
            }
            katalogp.commitTrx();
            initTab();
            
        }catch(Exception e){
            e.printStackTrace();
        }
        * */
    }//GEN-LAST:event_doSave

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        /*katalog = new Tkatalog(txtKode.getText().trim(),(String) cbMerk.getSelectedItem(), txtArtikel.getText().trim(), txtUkuran.getText().trim(), txtWarna.getText(),(String) cbTipe.getSelectedItem(),null);
               try{
        katalogp = new TkatalogJpaController(null,null);
            KWAMesg msg;
            katalogp.initTrx();
            
            msg = katalogp.destroy(katalog.getKode());
 katalogp.commitTrx();
                JOptionPane.showMessageDialog(null, msg.getMesg(),"Delete",1);
                initTab();

                    }catch(Exception e){
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cbTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipeActionPerformed

    private void cariBarang(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariBarang
        // TODO add your handling code here:
    }//GEN-LAST:event_cariBarang

    private void lblBarangDesccariBarang(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarangDesccariBarang
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBarangDesccariBarang

    private void cbSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSatuanActionPerformed

    private void lblBarang2cariBarang(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarang2cariBarang
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBarang2cariBarang

    private void lblBarang3cariBarang(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarang3cariBarang
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBarang3cariBarang

    private void lblBarang4cariBarang(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBarang4cariBarang
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBarang4cariBarang

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cbSatuan;
    private javax.swing.JComboBox cbTipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JLabel lblBarang;
    private javax.swing.JLabel lblBarang2;
    private javax.swing.JLabel lblBarang3;
    private javax.swing.JLabel lblBarang4;
    private javax.swing.JLabel lblBarangDesc;
    private javax.swing.JLabel lblPegawai;
    private javax.swing.JLabel lblPegawaiDesc;
    private javax.swing.JLabel lblToko;
    private javax.swing.JLabel lblTokoDesc;
    private javax.swing.JTable tabItem;
    private javax.swing.JFormattedTextField txtDiscount;
    private javax.swing.JFormattedTextField txtHarga;
    private javax.swing.JFormattedTextField txtJumlah;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtKlien;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtKodeBrg;
    private javax.swing.JTextField txtPegawai;
    // End of variables declaration//GEN-END:variables
    private Ttransbrgheader tbh;
    private TtransbrgheaderJpaController tbhp;
     private Ttransbrgitem tbi;
    private TtransbrgitemJpaController tbip;   

    private java.util.List<com.kwa.cittajaya.Ttransbrgitem> list;

    private class RowListener implements ListSelectionListener {
        
        public void valueChanged(ListSelectionEvent event) {
            if (event.getValueIsAdjusting()) {
                return;
            }
            tabItem.getSelectedRow();
            modelTransItem modelti = (modelTransItem) tabItem.getModel();
            tbi =  modelti.getData().get(tabItem.getSelectedRow());
            txtKodeBrg.setText(tbi.getTtransbrgitemPK().getKode());
            txtJumlah.setText(String.valueOf(tbi.getJumlah()));
            cbSatuan.setSelectedItem(tbi.getSatuan());
            txtHarga.setText(String.valueOf(tbi.getHarga()));
            txtDiscount.setText(tbi.getDiscount());
            
        }
    }

}
